# Generated by Django 4.0.10 on 2024-05-16 04:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=50, unique=True)),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'ADMIN'), (2, 'USER')], null=True)),
                ('full_name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(default='', max_length=100)),
                ('user_type', models.CharField(blank=True, choices=[('BD', 'BD'), ('DM', 'DM')], max_length=40)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('date_joined', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
