# Generated by Django 4.0.10 on 2024-05-16 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('BD', 'BD'), ('DM', 'DM'), ('Admin', 'Admin')], max_length=40),
        ),
    ]
